######################################
# AccelTool Configuration File
######################################

# Serial / base station
port=COM3
baudrate=3000000

######################################
# Wireless node

# Update with your node's address
nodeAddress=56384        
forceSetToIdle=true
configureNode=true
useSyncSampling=true
useLxrsPlus=true
# Updatate with your desired sample rate (e.g.1024, 2048, 4096.)
sampleRateHz=2048        
inactivityTimeoutSeconds=7200
unlimitedDuration=true

######################################
# Acquisition

# Set to a positive number to limit total samples, 0 for unlimited.
maxSamples=5000          
readTimeoutMs=10
 # Set to XY or XYZ
axisMode=XY
# Set Spec.             
spec=2.5

# Queues
rawQueueCapacityBatches=256
writeQueueCapacityBatches=256

# Display aggregation
displayAggregationSamples=100
outputDisplayCsvPath=display_data.csv

# Output
outputCsvPath=accel_data.csv
printToConsole=true
printEvery=100

# Debug
dumpSweepChannelsAtStartup=true
printCurrentNodeConfig=true

