######################################
# AccelTool Configuration File
######################################

# Serial / base station
port=auto
baudrate=3000000
autoFindComPort=true

######################################
# Wireless node
# 0 or auto means discover node address.
nodeAddress=56384
autoFindNodeAddress=true

# RF channel printed on the device label, valid range: 11-26.
frequency=11
autoFindNodeFrequency=true

# Update with your node's address      
forceSetToIdle=true
configureNode=true
useSyncSampling=true
useLxrsPlus=true

# Updatate with your desired sample rate (e.g.1024, 2048, 4096.)
sampleRateHz=2048  
timestampGapTolerancePercent=0.4 
inactivityTimeoutSeconds=7200
unlimitedDuration=true

######################################
# Acquisition

# Set to a positive number to limit total samples, 0 for unlimited.
maxSamples=0          
readTimeoutMs=10
 # Set to XY or XYZ
axisMode=XYZ
# Set Spec.             
spec=2.5

# Queues
rawQueueCapacityBatches=256
writeQueueCapacityBatches=256

# Display aggregation
displayAggregationSamples=200
outputDisplayCsvPath=display_data.csv

# Output
outputCsvPath=accel_data.csv
printToConsole=true

# Debug
dumpSweepChannelsAtStartup=true
printCurrentNodeConfig=true

